[tool.poetry]
name = "runner-py-evm"
version = "0.1.0"
description = ""
authors = ["Ziyad Edher <ziyad.edher@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
py-evm = "^0.12.1b1"
eth-utils = "<5"
lru-dict = { version = "^1.4.1", python = ">=3.9" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
